-- Snapshot of current database schema provided by user
-- This file represents the authoritative state of the database

-- 1. Cache Pacientes
create table public.cache_pacientes (
  id bigint generated by default as identity not null,
  patientid bigint null,
  telefone bigint null,
  nome text null,
  ultima_mensagem text null,
  ultima_msg_ia text null,
  notes text null,
  atualizado_em timestamp with time zone null,
  created_at timestamp with time zone null,
  session_id bigint null,
  aguardando_followup boolean null,
  numero_followup text null,
  lembrete text null,
  contexto text null,
  constraint cache_pacientes_pkey primary key (id),
  constraint cache_pacientes_patientid_key unique (patientid)
) TABLESPACE pg_default;

-- 2. Appointments
create table public.appointments (
  id uuid not null default gen_random_uuid (),
  patient_id bigint null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status text null default 'scheduled'::text,
  procedure_type text null,
  notes text null,
  metadata jsonb null default '{}'::jsonb,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  id_app_clinicorp bigint null,
  "Deleted" text null,
  "Canceled" text null,
  "Procedures" text null,
  status_id bigint null,
  date timestamp with time zone null,
  constraint appointments_pkey primary key (id),
  constraint appointments_patient_id_fkey foreign KEY (patient_id) references cache_pacientes (patientid) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_appointments_patient on public.appointments using btree (patient_id) TABLESPACE pg_default;
create index IF not exists idx_appointments_dates on public.appointments using btree (start_time, end_time) TABLESPACE pg_default;

-- 3. Bot Interactions
create table public.bot_interactions (
  id bigserial not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  conversation_id text not null,
  phone_number text not null,
  patient_id text null, -- NOTE: Text, not BigInt, so no FK to cache_pacientes
  patient_name text null,
  operation_type text null,
  status text not null,
  error_message text null,
  appointment_id text null,
  dentist_id text null,
  dentist_name text null,
  appointment_date date null,
  appointment_time time without time zone null,
  appointment_category text null,
  raw_data jsonb null,
  constraint bot_interactions_pkey primary key (id),
  constraint bot_interactions_status_check check (
    (
      status = any (array['success'::text, 'error'::text])
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_created_at on public.bot_interactions using btree (created_at desc) TABLESPACE pg_default;
create index IF not exists idx_operation_type on public.bot_interactions using btree (operation_type) TABLESPACE pg_default where (operation_type is not null);
create index IF not exists idx_status on public.bot_interactions using btree (status) TABLESPACE pg_default;
create index IF not exists idx_phone_number on public.bot_interactions using btree (phone_number) TABLESPACE pg_default;
create index IF not exists idx_patient_id on public.bot_interactions using btree (patient_id) TABLESPACE pg_default where (patient_id is not null);
create index IF not exists idx_dentist on public.bot_interactions using btree (dentist_name) TABLESPACE pg_default where (dentist_name is not null);
create index IF not exists idx_appointment_id on public.bot_interactions using btree (appointment_id) TABLESPACE pg_default where (appointment_id is not null);
create index IF not exists idx_raw_data_gin on public.bot_interactions using gin (raw_data) TABLESPACE pg_default;

-- create trigger update_bot_interactions_updated_at BEFORE update on bot_interactions for EACH row execute FUNCTION update_updated_at_column ();
